SELECT 
    BEJEGYZES.*, 
    VFELHASZNALO.FELHASZNALO_ID,
    VFELHASZNALO.NEV, 
    VBEJEGYZES_CIMKE.TAGEK 
FROM 
    BEJEGYZES
    INNER JOIN VFELHASZNALO ON VFELHASZNALO.FELHASZNALO_ID = BEJEGYZES.SZERZO_FELHASZNALO_ID
    LEFT JOIN VBEJEGYZES_CIMKE ON VBEJEGYZES_CIMKE.BEJEGYZES_ID = BEJEGYZES.BEJEGYZES_ID
WHERE 
    BEJEGYZES.SZERZO_FELHASZNALO_ID = :userid
    OR BEJEGYZES.SZERZO_FELHASZNALO_ID IN (
        SELECT 
            CASE WHEN (KEZDEMENYEZO_FELHASZNALO_ID = :userid) THEN CEL_FELHASZNALO_ID ELSE KEZDEMENYEZO_FELHASZNALO_ID END as masik
        FROM 
            FELHASZNALO_KAPCSOLAT
        WHERE 
            (KEZDEMENYEZO_FELHASZNALO_ID = :userid OR CEL_FELHASZNALO_ID = :userid) AND FELHASZNALO_KAPCSOLAT.TIPUS = 1
    )
    ORDER BY LETREHOZVA DESC
